### ISSUE TITLE
[BUG] Domains are not fetched from Shopware instance

### ISSUE THREAD

**Issue by willopez** [vuestorefront/shopware-pwa#1343]
### Describe the bug

I followed the instructions on installing the pwa canary version and I get the following error when executing this command: 
`npx @shopware-pwa/cli@canary init`

Error: 
```
Please provide username and password for plugins authentication. You can leave the fields empty if connecting to demo instance or if you don't need plugins :)
✔ Shopware admin username: · admin
✔ Shopware admin password: · ********
✔ Do you want to allow dev mode for slots? (Don't use for production!) (y/N) · false
UNEXPECTED ERROR [object Object]
✔ Generating plugins files
Shopware languages refreshed
Plugins generated
CMS prepared
Shopware languages refreshed
```

Not sure what the `UNEXPECTED ERROR [object Object]` is, but the end results is that the `domains.json` is an empty object and the `languages.json` seems to be populated correctly:

```
{
  "en-US": {
    "id": "2fbb5fe2e29a4d70aa5854ce7ce3e20b",
    "code": "en-US",
    "name": "English"
  },
  "de-DE": {
    "id": "48748d8b982b4224925959b62a473b6d",
    "code": "de-DE",
    "name": "German"
  }
```

The app fails to start.

In the Shopware instance access logs I see the following 500 error 
```
- [04/Feb/2021:17:23:56 +0000] "GET //pwa/866f04b9e45b1a938800b6f730fe1db5.json HTTP/1.1" 500 843 "-" "axios/0.21.1"
shopware_1  | 172.18.0.2 - - [04/Feb/2021:17:23:56 +0000] "GET /store-api/v3/language HTTP/1.1" 200 2091 "-" "axios/0.21.1"
```

### Additional context

Using: 
`shopware-pwa/shopware-pwa 2.0`
`Shopware 6.3.5.0`

**Comment by elkmod** [comment]
@willopez thanks for reporting! Could you check whether `shopwareEndpoint` in your `shopware-pwa.config.js` contains a trailing `/`? If so, try removing it and re-initialising.

Dom

**Comment by willopez** [comment]
@elkmod I does not, just to verify this is correct,  my `shopwareEndpoint` is set to a URL of a storefront, in my case the headless storefront and it has a domain set, which is what I am setting `shopwareEndpoint` to. This is the URL that returns a 500 error, `https://pwa-api.willopez.com//pwa/866f04b9e45b1a938800b6f730fe1db5.json` that is my sales channel url. 

And I see this error when starting the PWA:
![image](https://user-images.githubusercontent.com/486340/107120859-ff9db800-6854-11eb-9610-bf0855bcf045.png)

Further, the unexpected error in the CLI seems to be coming from this call: https://github.com/vuestorefront/shopware-pwa/blob/792eca1f9ad7d2e638249a0521c5d52bf2906782/packages/cli/src/extensions/plugins-extensions.ts#L38

There is no try catch so the error just gets swallowed up. My understanding is that the plugin configuration should be retrieved using the Admin API, however, that request uses the value in `shopwareEndpoint` which points to the sales channel, I guest the Admin API is accessible via that URL?

**Comment by willopez** [comment]
Also, unrelated to this, but I attempted to join the pwa slack channel, but the invite has expired in the link in the README. Please update, thanks.

**Comment by elkmod** [comment]
Hi @willopez!

First of all - I am able to run a local version of shopware-pwa with your API, so it is working perfectly fine.

Let my try to clarify:

`shopwareEndpoint` is the URL which all API requests paths are built made relative to. It has nothing to with the domain configuration of your sales channel. A good indication is the URL of your admin panel. In your case it is located at `https://pwa-api.willopez.com/admin`. Hence, the root path of your Shopware instance - the `shopwareEndpoint` is `https://pwa-api.willopez.com` **(without a trailing `/`)**

`shopwareAccessToken` is used to identify the sales channel for your PWA

`pwaHost` is the URL relative to which you want your frontend application to do the routing. It is tied to the domain configuration of your sales channel. **If** your sales channel has only a single configured domain (which CAN be the same as `shopwareEndpoint`, but by no means has to), set `pwaHost` to the same value (again without trailing `/`).

If however, you're going to configure multiple domains (which in Shopware wording can also mean suffixes rather than just domains) like
 * `https://pwa-frontend.willopez.com/us`
 * `https://pwa-frontend.willopez.com/gb`
 * `https://pwa-frontend.willopez.com/whatever`

they would share the common `pwaHost` which in that case would be `https://pwa-frontend.willopez.com`. The `shopwareEndpoint` in that case would remain the same as before.

Try the following configuration for `shopware-pwa.config.js`, it worked for me

```
module.exports = {
  shopwareEndpoint: "https://pwa-api.willopez.com",
  shopwareAccessToken: "SWSCYTV6VLPJQNVUCENOQNO5QW",
  pwaHost: "https://pwa-api.willopez.com",
};
```

PS: You should be able to join the slack channel without an explicit invitation (we will remove the old one from the README) - [VSF Slack Channel](https://vuestorefront.slack.com)

**Comment by willopez** [comment]
@elkmod Got it, I was just confused as to the mapping of the domains, everything is working now. Thanks! and great work on this project.
