### ISSUE TITLE
[BUG] ProductListing Filter unnecessary API call

### ISSUE THREAD

**Issue by Laggertron** [vuestorefront/shopware-pwa#1424]
### Describe the bug
Setting a filter in Product Listing is making an API call to receive the filtered Productlist. In addition to this request the PWA is making another call to the API without the Filters (with a limit of 24). This additional Request is blocking the listing loading and results in an increased load time (more than 100%) since the API is calles once with filters and once more without.

Reproduction:
- Open category with product listing
- Open filter sidebar
- set any Filter
- XHR Callstack is: product-listing/{categoryId} (with set filters) -> context -> context -> product-listing/{categoryId} (without set filters and response limit set to 24)

**Comment by Laggertron** [comment]
https://shopware-pwa.storefrontcloud.io/Doswiadczenie/
Click Filter and select any size to reproduce

**Comment by mkucmus** [comment]
@Laggertron thanks for being alert :) 
I'm almost sure the second call was due to an issue that apparently no longer exists, I mean: `aggregation` properties were narrowed down, after some filter is applied to the listing. We were calling second time without any filters to get the list of available filters. Just because the filters components is bound to the aggregation response. Cool we finally can get rid of it 👍🏻 thanks!
