### ISSUE TITLE
[BUG] user is logged in after purchase

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1435]
### Describe the bug
Buying things while I'm not logged in. I'm not creating account during payments step and after purchase I'm logged in...
I should be logged out because in admin panel I specified it.
![image](https://user-images.githubusercontent.com/30865830/115234892-d84b4d00-a119-11eb-98b5-a561e7afde4b.png)

Nevertheless I can't even logout or make another purchase because plenty of errors f. ex. while I'm trying to logout
![image](https://user-images.githubusercontent.com/30865830/115235830-e9e12480-a11a-11eb-8255-16227116c313.png)

### Additional context
Shopware v6.3.5.1 Stable Version
Shopware PWA 0.7.1

**Comment by develth** [comment]
IMHO he still needs to be logged in on order.vue page, because there is a lot of Context-Related stuff to fetch.
Maybe logout on leaving that page?

**Comment by niklaswolf** [comment]
@patzick This is still relevant in SW 6.4 and shopware-pwa 0.9.x

After completing a purchase as a guest customer (which many customers are) the user is still logged in and has access to "my account" etc. This is not only highly confusing for the customer, as he didn't want to create an account.

**Comment by patzick** [comment]
@niklas-wolf this was the issue with API endpoint, fix will be released with 6.4.1.1 and we'll be able to add missing logic here. There will be:
- availability to log out the guest user
- availability to get the list, add and change guest user addresses

For sure we'll have a distinction, that guest user cannot go into my account. My proposition is to have "Guest session as NAME" with "end session" button.

This checkbox is purely on the backend side, if it's checked the session should be invalidated, I wouldn't put logic responsible for that on the frontend side. We'll test this when the fix is provided and if there still is a problem with that, we'll pass it to Shopware 6 core team.

Does it sound good for you Folks? :)
cc @elkmod @mkucmus

**Comment by niklaswolf** [comment]
@patzick  I'm not sure about "Guest session as NAME" ... 
This is not something the user expects since they stated that they want a guest checkout, thus it's highly likely that they will not browse the shop further in their current session. I think it'd be fully sufficient to automatically end the guest session when visiting the checkout-success page. You can use the session there to fetch the necessary information about the order to display the page, after that the session is no longer needed...
But that's just my two cents on this topic.
