### ISSUE TITLE
[BUG] Endpoint used by shopware-pwa languages results in 404

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1533]
### Describe the bug
When running the command `shopware-pwa languages` or `shopware-pwa dev` with the new version of the PWA and SW6.4 it will throw an error that the languages route is not found. This is due to the old versioning used in SW6.3. This error will be thrown in the terminal.

Now it still uses `/store-api/v3/language` but this has to be `/store-api/language` right?

<!-- Provide reproduction steps1, example
run `shopware-pwa languages` or `shopware-pwa dev`

<img width="588" alt="Screenshot 2021-06-07 at 09 28 39" src="https://user-images.githubusercontent.com/55089200/120978789-21f90100-c775-11eb-857e-86d176117b2a.png">

**Comment by mkucmus** [comment]
hi @meeshoogendoorn, could you ensure what's the version of shopware-pwa you are on? 
because being on canary there is no such error.
It's always better and safer to use the npx's canary version - then you will be always up to date with no dependency issues :)

![image](https://user-images.githubusercontent.com/5596960/120979293-bf543500-c775-11eb-9ade-b4602f970c9d.png)

**Comment by meeshoogendoorn** [comment]
Hey @mkucmus 

I updated the cli last week at the same time i updated shopware-pwa to version 0.9

I will use npx from now on thanks for your reply💪

**Comment by meeshoogendoorn** [comment]
I tested it and it works

**Comment by mkucmus** [comment]
great! so I'm closing it 💙
