### ISSUE TITLE
[BUG] Using SwTopNavigation out of position

### ISSUE THREAD

**Issue by PaulSchumacher** [vuestorefront/shopware-pwa#1537]
I'm trying to use the SwTopNavigation outside the SfHeader navigation slot. This causes the navigation content to be removed because the Navigation Element offsetTop is greater than 27.

Is this expected behaviour or shouldn't this component be used outside the SfHeader slot on another position?

You can reproduce this bug/behaviour by either adding marginTop to the SwTopNavigation or by placing the SwTopNavigation behind the SfHeader.
1. shopware-pwa o
2. select SwHeader
3. add margin-top to the SwTopNavigation

SwHeader.vue
```
<template>
  <div class="sw-top-navigation" data-cy="main-header">
    <SwCookieBar />

    <SwTopBar />

    <SfHeader
      :title="$t('page.title')"
      class="sw-header sf-header--has-mobile-search"
      :has-mobile-search="false"
      :is-nav-visible="true"
      :is-sticky="false"
    >
      <template #logo>
        <SwLogo />
      </template>
      <template #navigation>
        <div style="margin-top: 10px">
          <SwTopNavigation />
        </div>
      </template>
      <template #search>
        <SwSearchBar />
      </template>
      <template #header-icons>
        <SwHeaderIcons />
      </template>
    </SfHeader>

    <div class="bsn-navigation">
      <SwTopNavigation />
    </div>
  </div>
</template>
```

The Code that causes the bug in the SwTopNavigation
```
navElements.forEach((element) => {
  if (element.offsetTop <= 27) {
    visibleItemsCount += 1
  }
  if (element.offsetTop > 27) {
    unvisibleItemsCount += 1
  }
})

if (unvisibleItemsCount >= 1) {
  // This subtraction makes more space in nav and prevent to move "more category " to the next line.
  this.unwrappedElements = Math.max(0, visibleItemsCount - 2)
} else {
  this.unwrappedElements = visibleItemsCount
}
```

**Comment by rittou** [comment]
In order to play with **SwTopNavigation** out of **SfHeader**, we created a new component called **SwTopNavigationContainer**. You guys can use it to make it possible by using it, using **SwTopNavigationContainer** to cover the **SwTopNavigation** inside and other contents you want to have. 
![Screenshot from 2022-06-15 09-36-13](https://user-images.githubusercontent.com/85224631/173726526-78967c49-1c47-4ba1-aa17-dde8e27841e1.png)

Specifically for the reason that causes this problem, **SwMegaMenu** inside **SwTopNavigation** has `position: absolute`, so it needs a parent container to have `position: relative` to make it behave as expected.
