### ISSUE TITLE
[BUG] /account is display as logged out user

### ISSUE THREAD

**Issue by BeeJayJayn** [vuestorefront/shopware-pwa#1561]
### Description

`/account` can be manually accessed as a logged out user and is displaying the UI. This should IMO be resolved by displaying the login modal on a blurred background. Closing the modal returns the user to the previous page or homepage.

PWA 0.9.1
SW 6.4

**Comment by meeshoogendoorn** [comment]
Same issue here, Something is going wrong with the route object in the `auth.js` middleware. My object looks like this: 
```bash 
fullPath: "/account/profile"
hash: ""
matched: (2) [{…}, {…}]
meta: (2) [{…}, {…}]
name: "undefined_profile_334d47a1d61f46c6adc292ad7bdb9714"
params: {}
path: "/account/profile"
query: {}
```

The middleware is checking if the route is protected by it's name property but it got undefined and an id as name since the update. Guess the middleware is still correct but the issue is the name that's incorrect.
