### ISSUE TITLE
[BUG] Advanced pricing in cart (total an subtotal)

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1650]
### Project type
- [0.9.2 ] Project (generated by CLI)
- [] Contribution (cloned/forked from GH)

### Describe the bug
<img width="409" alt="Screenshot 2021-08-31 at 11 10 17" src="https://user-images.githubusercontent.com/55089200/131476216-9b9a49df-f4a6-4979-a946-34c78a48cb90.png">

As u can see the line item has advanced pricing for the corresponding product. This all works very well but the total and subtotal price are incorrect in the SwTotals.vue. I also use a list price on the advanced pricing settings.

<img width="1395" alt="Screenshot 2021-08-31 at 11 16 50" src="https://user-images.githubusercontent.com/55089200/131476757-76201c7f-7585-4957-a373-41947de59053.png">

### Problem
incorrect total price using `useCart` composable.

```js
   const {
      cartItems,
      count,
      subtotal,
      totalPrice,
      shippingTotal,
      removeItem,
    } = useCart(root)
```

### Additional context
- node version: 14
- shopware-pwa version: 0.9.2
- system:  Macos Big Sur

**Comment by mkucmus** [comment]
@meeshoogendoorn thanks for reporting the issue.
I've checked what the behavior looks like, and the placed order has the same totals and subtotals as it's during the checkout (visible on pwa), so it looks like the list price was ignored. Maybe there is some step I missed 🤔 


here's the logic responsible for getting total and subtotal price, we don't do any calculations on client side, maybe you will find something wrong here:
```js
const totalPrice = computed(() => {
    const cartPrice =
      cart.value && cart.value.price && cart.value.price.totalPrice;
    return cartPrice || 0;
  });


  const subtotal = computed(() => {
    const cartPrice = cart.value?.price?.positionPrice;
    return cartPrice || 0;
  });
```

What is an expected behavior in this case?

placed order:
![Screenshot from 2021-08-31 15-19-35](https://user-images.githubusercontent.com/5596960/131509632-666abab8-30d1-46a6-b2b9-dd685f6ff497.png)

product configuration:
![Screenshot from 2021-08-31 15-18-55](https://user-images.githubusercontent.com/5596960/131509634-d7638d30-7075-451d-a505-678b6629ffbb.png)

**Comment by meeshoogendoorn** [comment]
In your case the costs would be 40 and a total of 120, Is how i see it. Because list price is the discounted price. But maybe this is going wrong in the Shopware Store api and not in the PWA because of no calculations made. The thing that set me thinking about this was that in PWA the lineItems show the correct discounted price in cart. Only the total and subtotal are incorrect. But as i can see in your image of Shopware 6 Administration it is probably something that is ignored by Shopware 6 itself.

**Comment by mkucmus** [comment]
I found the resource that explains list price as [(Recommended Retail Price)](https://docs.shopware.com/en/shopware-6-en/catalogues/products#prices). That means that we need to adjust the displaying logic to follow that rule:
show list price as an old price when the `price` is lower than `list price`. 

exceptional price logic
```
if (list price > price) {
 discounted price = price
 old price = list price
}
```

It's close to "special price" "regular price" that is crossed out - mechanism but I can be wrong.

**Comment by mkucmus** [comment]
The logic is already covered. According to the documentation: list price should be used only to point a price before a discount (if it's set - this will be displayed as regular price, but not actual price). 
that's the correct setup:
![image](https://user-images.githubusercontent.com/5596960/134975330-62db0839-8d75-4648-ace9-dfbb47ebc3c1.png)

then the totals look like:
![image](https://user-images.githubusercontent.com/5596960/134975426-95eb725c-3e47-403c-8e31-0f519d4a8217.png)
