### ISSUE TITLE
[Bug] serverMiddleware can't be found

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1715]
### What happened?

When trying to add a server middleware following the nuxt docs (https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware/#custom-server-middleware) I get the following error when building the app in production mode
```
 Nuxt Fatal Error
   │   Error: Cannot resolve "~/server-middleware/myMiddleware.js" from   │
   │   "/app/server-middleware/myMiddleware.js"
```

### Steps To Reproduce

1. add custom server-middleware in `src/server-middleware` following the nuxt docs
2. add the server middleware to the nuxt config
`  serverMiddleware: ["~/server-middleware/myMiddleware.js"],`
3. build the app for production mode

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Previous versions (write which one)

### Environment

```markdown
- OS: Unix
- Node: v14.17.6
- Shopware API: irrelevant
- Shopware PWA version: 1.0.0-RC.1
```

**Comment by patzick** [comment]
Hey @niklaswolf 
this is unfortunately caused by the nuxt config, as the aliases are not copied to runtime config.
I would recommend a similar approach to yours:
`serverMiddleware: ["./server-middleware/something.js"]`
and having `server-middleware` directory in the root folder

We want to take advantage of server middleware in near future after 1.0.0 stable release, so we'll make this part better!

Is that workaround good for you for now?

**Comment by niklaswolf** [comment]
@patzick yeah I can work with the workaround, no problems. I just wanted to raise this issue as I came across it and document a solution for others, because it's not so intuitive (especially when you try to follow the nuxt docs)

**Comment by patzick** [comment]
I agree and we'll address this issue in future! Thanks :)
