### ISSUE TITLE
[Bug] sw-context-token not working properly

### ISSUE THREAD

**Issue by henrikawl** [vuestorefront/shopware-pwa#1749]
### What happened?

So I am working with store-api to crate customers and work with the shop. 
So when I create a customer I get sw-context-token, which is the same as cart ID and I can perform customer shop interactions with that (Fetch a cart, add items, create an order).
The strange thing happening is that after registering a customer, after approx 1 day, when I fetch a cart with the same context-token it fetches different carts every time. When I check if customer is logged in with that token it brings all the customer information with that token, but when trying to fetch a cart it acts like not logged in customer and generates a random cart every time. If I try to create an order with that token, it says cart is empty. If I try to create an order with randomly generated cart id (new context token) it says customer is not logged in.
Am I missing something?

### Steps To Reproduce

1. Create a customer
2. Fetch a cart
3. Add items to the cart
4. Create an order
5. Wait 24 hours
6. Fetch a cart again and it doesn't bring the same token as you have put in the header. It brings cart with randomly generated token. But it had to be the same

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Environment

```markdown
- OS: Ubuntu 20.04.1 LTS
- Node: 14
- Shopware API: 6.4.0
- Shopware PWA version: 1.0.0-RC.1
```

**Comment by mkucmus** [comment]
Hi @henrikawl! thanks for reporting.
I'm not sure if it's due to an old version of Shopware 6 (you noted v6.4.0.0) or something different.

In general, Shopware PWA is only an API Client, which means that we are not setting/invoking a token change and the application only receive the token and if it changes - the same token is being saved under a cookie. In that model "client/receiver" we actually don't know why token is changing or when, and what's behind it. We just set it and send further request with current token. If you find that behavior of session handling is wrong, please report it at the [Shopware 6 Core project](https://github.com/shopware/platform/issues).

**Comment by henrikawl** [comment]
Thanks for the response @mkucmus ! Will check there
