### ISSUE TITLE
[Bug] HMR not working with custom theme

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [vuestorefront/shopware-pwa#1793]
### What happened?

I have init a new project and create a new theme with the following command:
`npx @shopware-pwa/cli create-theme`

Everything is fine. But i expect that the HMR also working for custom themes. If i change a file in my new theme the console say Updated file but nothing happen.

### Steps To Reproduce

1. Init new project: `npx @shopware-pwa/cli init`
2. Edit shopware-pwa.config.js file and add: `theme: "default-blank"`
3. Create new theme: `npx @shopware-pwa/cli create-theme` (Theme name: default-blank)
4. Go to the folder default-blank and run `yarn dev`
5. Change any file nothing happen.
6. Go back to root and run `yarn dev`. If you change any files in the theme i got the message: "Updated" but HMR not working. In the browser i can't see the changes.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

CLI, nuxt-module

### Environment

```markdown
- OS: MacOSX
- Node: 14
```

**Comment by mkucmus** [comment]
Hi @Maximilian-Schwarz, as always thanks for reporting the issue!

I've got bad news... I couldn't reproduce the issue 👎🏻 But... let's try to wrap it up and see what may go wrong.

Before I started reproducing. I had removed my all (yes 😎 ) yarn links (under `~/.config/yarn/link`) because I've got few  projects, generated, related to each other and so on... to avoid problem with linking the wrong project - I've removed it all (don't do this if you haven't got a backup of it ;) )

then I created exactly what you did. so I was able to:
- run dev mode in my new "default-blank" directory (it's important to do so first)
- run a root nuxt project (with updated shopware-pwa.config.js file)

after that, I put the new page to the theme src/pages directory, the appropriate message was shown "[CLI > dev-theme] Changed file: src/pages/test.vue" and them the root project rebuilt itself successfully. The same thing happened when I put the component into src/components/

So from that perspective - it does work, but we are open for your feedback/suggestion, maybe something is unclear or unintuitive - please share you opinion with us 👍🏻

**Comment by mkucmus** [comment]
closing it due no response.
