### ISSUE TITLE
[SPIKE] Handling Cart items against User Login / Logout

### ISSUE THREAD

**Issue by rmakara** [vuestorefront/shopware-pwa#220]
* User not logged in with sth in the cart then login to empty cart.
* User not logged in with sth in the cart then login to sth in the cart.
* User logged in with sth in the cart then logout.
* Handle case of login with the same products in the cart.
* Handle case of login with different products in the cart.
* Handle case of login with same & different products in the cart.

**Comment by rmakara** [comment]
@mkucmus @akrajna 
Probably it was already tested and solved? :)

**Comment by akrajna** [comment]
It does not work properly:
**Current behavior**: If logged in user has products in cart, then after logging out, there is still the product in the cart. If user clears the cart after logging out and then login again the cart is empty.
![Login](https://user-images.githubusercontent.com/57936972/76425179-8fb75100-63a9-11ea-9457-f73ac8384efd.gif)


**Expected behavior**:  If logged in user has products in cart, then after logging out, cart should be empty. After logging in again for the same account, items should appear in cart again.

**Comment by rmakara** [comment]
CC: @elkmod @patzick

**Comment by akrajna** [comment]
It still does not work properly. 
* **Actual behavior:** If logged in user has products in cart, than after logging out, cart still have the products in. 
   **Expected behavior:** If logged in user has products in cart, than after logging out, cart should be empty.
* **Actual behavior:** logged in user has some products in the cart, than after logging out, if user deletes items from the cart and log in again the cart is empty.  
   **Expected behavior:** logged in user has some products in the cart, then after logging out, the cart is empty and if user logged in again for the same account items should appear in the cart again

**Comment by mkucmus** [comment]
1. User not logged in with sth in the cart then login to empty cart.

2. User not logged in with sth in the cart then login to sth in the cart.
3. User logged in with sth in the cart then logout.
4. Handle case of login with the same products in the cart.
5. Handle case of login with different products in the cart.
6. Handle case of login with same & different products in the cart.

> * **Actual behavior:** If logged in user has products in cart, than after logging out, cart still have the products in.
confirmed - still exists
>   **Expected behavior:** If logged in user has products in cart, than after logging out, cart should be empty."

> * **Actual behavior:** logged in user has some products in the cart, than after logging out, if user deletes items from the cart and log in again the cart is empty.
confirmed - still exists
>   **Expected behavior:** logged in user has some products in the cart, then after logging out, the cart is empty and if user logged in again for the same account items should appear in the cart again

hi @elkmod , can you have a look at this? We need a confirmation that's the way it works and it's not a bug, because we've got a little bit different experiences from other platforms. We are not saying it's a bad practice, or not intuitive :)

**Comment by mkucmus** [comment]
API works as expected regarding cart items handling. Moreover, even if it's not working in the future, the appropriate issue should be created on API core side.
