### ISSUE TITLE
[BUG] no login credentials

### ISSUE THREAD

**Issue by ivosanchez** [vuestorefront/shopware-pwa#559]
for the demo backend, there are a url and a token , but there are not admin login credentials.

**Comment by patzick** [comment]
Hey @ivosanchez, we cannot give the public access to demo instance because it could cause disturbance for our work and weird CMS pages :)
Skipping this credentials will not have consequences other than displaying plugins from demo instance in your local instance.

How do you see solution for this?

Propositions which currently comes to my mind:
- not asking for username and password when using demo instance
- some section in docs which would explain that you can safely  skip this credentials (I'd need your help where would be most helpful to put that kind of information)

**Comment by ivosanchez** [comment]
it is ok. after all, that demo instance is prolly used by most people to see how well it works.  And  I think that a note saying that when prompt asks you for the credentials you can leave them blank and go ahead.

**Comment by ivosanchez** [comment]
Actually, thinking more about it, Saleor has a demo that allows to get in the backend for a while and  then it resets itself so any likely changes made during the session don't persist. It might be too complicated to implement and not worth it (?)

**Comment by patzick** [comment]
Not in the current scope, I'm afraid, but for sure something we will discuss with Shopware team :)

## Acceptance criteria
- [ ] CLI informs that shopware credentials are not mandatory to run your instance

**Comment by patzick** [comment]
closing this one as with Dockware solution this is no longer an issue. The demo instance is used for test envs and playing with Shopware locally gives more power to the user https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/local-environment.html#shopware-instance-in-10-seconds
